name: Win64
on:
  push:
jobs:
  build-win64:
    name: Win64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
      - name: Release(Win64)
        uses: threeal/cmake-action@main
        with:
          source-dir: OCCT
          build-dir: build-release
          generator: "Visual Studio 17 2022"
          build-args: -t install --config Release
          args: -DCMAKE_INSTALL_PREFIX=dist -DUSE_TK=OFF -DUSE_FREETYPE=OFF -DBUILD_MODULE_Draw:BOOL=FALSE -DBUILD_MODULE_DataExchange:BOOL=TRUE -DBUILD_MODULE_OpenGL:BOOL=FALSE -DBUILD_MODULE_Visualization:BOOL=FALSE -DUSE_OPENGL:BOOL=FALSE -DCMAKE_BUILD_TYPE=Release
      - name: Package
        run: nuget pack occt.win64.nuspec
      - name: Push
        run: nuget push *.nupkg --source https://api.nuget.org/v3/index.json 

